import os
import pandas as pd
import json

'''
json_path: pat of json file generated by Label-studio
contains bounding boxes coordinates (x, y, w, h) and classes
as a percentage of img size.

out_path: path where to put the files with [class, x, y, w, h] of each img

img_path: path with folders with images. For label dictionary.
'''
json_path = './detection_dataset/bboxes'
out_path = './detection_dataset/bboxes/'
img_path = './detection_dataset/dataset'

def box_values_generator(json_path, out_path, img_path):

    labels = sorted(os.listdir(img_path))
    label_dict = {labels[i]:i for i in range(0, len(labels))}

    with open(os.path.join(json_path , 'bird_bboxes.json'), 'r') as j:
            bb_file = json.load(j)

    # 
    def get_bbox(value):
        hl_x = value['x']
        hl_y = value['y']
        width = value['width']
        height = value['height']
        bbox_x = hl_x + (width / 2)
        bbox_y = hl_y + (height / 2)
        return bbox_x/100, bbox_y/100, width/100, height/100

    for idx in range(len(bb_file)):
        img_name = bb_file[idx]['file_upload'][:9]
        detections = bb_file[idx]['annotations'][0]['result']
        values = [det['value'] for det in detections]
        
        objects = []
        for value in values:
            label = label_dict[value['rectanglelabels'][0]]
            x, y, w, h = get_bbox(value)
            objects.append([label, x, y, w, h])
            
        boxes_path = out_path + '/' + img_name + '.txt'
        with open(boxes_path, 'w') as wf:
            for object in objects:
                object_values = ''
                for val in object:
                    object_values += (str(val) + ' ')

                wf.write(object_values +'\n')
        print('Store all bounding boxes from {0} in file {1}'.format(img_name, boxes_path))

box_values_generator(json_path, out_path, img_path)